// <auto-generated />
using System;
using DELICATA_ELEGANZA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DELICATA_ELEGANZA.Migrations
{
    [DbContext(typeof(DelicataContext))]
    partial class DelicataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.Capacidades", b =>
                {
                    b.Property<int>("id_capacidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_capacidad"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_capacidad");

                    b.ToTable("Capacidades");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.Categorias", b =>
                {
                    b.Property<int?>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("id_categoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_categoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.Generos", b =>
                {
                    b.Property<int>("id_genero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_genero"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_genero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.Marcas", b =>
                {
                    b.Property<int?>("id_marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("id_marca"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_marca");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.Materiales", b =>
                {
                    b.Property<int?>("id_material")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("id_material"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_material");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.ProductoImagenes", b =>
                {
                    b.Property<int>("id_imagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_imagen"));

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_producto")
                        .HasColumnType("integer");

                    b.HasKey("id_imagen");

                    b.HasIndex("id_producto")
                        .HasDatabaseName("IX_ProductoImagenes_Producto");

                    b.ToTable("ProductoImagenes");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.Productos", b =>
                {
                    b.Property<int>("id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_producto"));

                    b.Property<decimal?>("Alto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ancho")
                        .HasColumnType("numeric");

                    b.Property<int?>("CantidadRuedas")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Compartimentos")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Diametro")
                        .HasColumnType("numeric");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<bool?>("FuelleExpandible")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Profundidad")
                        .HasColumnType("numeric");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer");

                    b.Property<int?>("id_capacidad")
                        .HasColumnType("integer");

                    b.Property<int?>("id_categoria")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "IdCategoria");

                    b.Property<int?>("id_genero")
                        .HasColumnType("integer");

                    b.Property<int?>("id_marca")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "IdMarca");

                    b.Property<int?>("id_material")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "IdMaterial");

                    b.Property<int?>("id_tipo")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "IdTipo");

                    b.Property<int?>("id_tipo_cierre")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "IdTipoCierre");

                    b.HasKey("id_producto");

                    b.HasIndex("Disponible")
                        .HasDatabaseName("IX_Productos_Disponible");

                    b.HasIndex("id_capacidad");

                    b.HasIndex("id_categoria")
                        .HasDatabaseName("IX_Productos_Categoria");

                    b.HasIndex("id_genero");

                    b.HasIndex("id_marca")
                        .HasDatabaseName("IX_Productos_Marca");

                    b.HasIndex("id_material");

                    b.HasIndex("id_tipo");

                    b.HasIndex("id_tipo_cierre");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.Tipos", b =>
                {
                    b.Property<int?>("id_tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("id_tipo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_tipo");

                    b.ToTable("Tipos");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.TiposCierre", b =>
                {
                    b.Property<int>("id_tipo_cierre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_tipo_cierre"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_tipo_cierre");

                    b.ToTable("TiposCierre");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuarios_Correo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.ProductoImagenes", b =>
                {
                    b.HasOne("DELICATA_ELEGANZA.Models.Productos", "Producto")
                        .WithMany("Imagenes")
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.Productos", b =>
                {
                    b.HasOne("DELICATA_ELEGANZA.Models.Capacidades", "Capacidad")
                        .WithMany()
                        .HasForeignKey("id_capacidad")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DELICATA_ELEGANZA.Models.Categorias", "Categoria")
                        .WithMany()
                        .HasForeignKey("id_categoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DELICATA_ELEGANZA.Models.Generos", "Genero")
                        .WithMany()
                        .HasForeignKey("id_genero")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DELICATA_ELEGANZA.Models.Marcas", "Marca")
                        .WithMany()
                        .HasForeignKey("id_marca")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DELICATA_ELEGANZA.Models.Materiales", "Material")
                        .WithMany()
                        .HasForeignKey("id_material")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DELICATA_ELEGANZA.Models.Tipos", "Tipo")
                        .WithMany()
                        .HasForeignKey("id_tipo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DELICATA_ELEGANZA.Models.TiposCierre", "TipoCierre")
                        .WithMany()
                        .HasForeignKey("id_tipo_cierre")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Capacidad");

                    b.Navigation("Categoria");

                    b.Navigation("Genero");

                    b.Navigation("Marca");

                    b.Navigation("Material");

                    b.Navigation("Tipo");

                    b.Navigation("TipoCierre");
                });

            modelBuilder.Entity("DELICATA_ELEGANZA.Models.Productos", b =>
                {
                    b.Navigation("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
